# Generated by Django 3.2 on 2022-10-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleID', models.IntegerField()),
                ('username', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('article', models.CharField(max_length=20000)),
                ('PostTime', models.CharField(max_length=100)),
            ],
        ),
    ]
