# Generated by Django 3.2 on 2022-10-29 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_rename_article_articleinfo_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleinfo',
            name='PostTime',
        ),
    ]
