# Generated by Django 3.2 on 2022-10-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_remove_articleinfo_posttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleinfo',
            name='articleID',
            field=models.CharField(max_length=200),
        ),
    ]
