# Generated by Django 3.2 on 2022-10-29 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_alter_articleinfo_articleid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleinfo',
            old_name='articleID',
            new_name='ArticleID',
        ),
    ]
