# Generated by Django 3.2 on 2022-10-29 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_rename_articleid_articleinfo_articleid'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleinfo',
            name='PostTime',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='articleinfo',
            name='ArticleID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='articleinfo',
            name='content',
            field=models.CharField(default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='articleinfo',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='articleinfo',
            name='username',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(default='', max_length=32),
        ),
    ]
