# Generated by Django 3.2 on 2022-10-29 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20221029_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleinfo',
            old_name='ArticleID',
            new_name='seed',
        ),
    ]
